<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.13">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.13" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.13" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.13" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="9.0.13" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.13" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="9.0.13" />
    <PackageVersion Include="Microsoft.Extensions.Options.DataAnnotations" Version="9.0.13" />
    <PackageVersion Include="Microsoft.Management.Infrastructure" Version="3.0.0" />
    <PackageVersion Include="Microsoft.Web.WebView2" Version="1.0.4022.49" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup Label="Tests">
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageVersion Include="NSubstitute" Version="5.3.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.0.2" />
  </ItemGroup>
</Project>