// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wec.Infrastructure.Persistence;

#nullable disable

namespace Wec.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WecDbContext))]
    [Migration("20260702120332_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("Wec.Modules.Inventory.Persistence.HardwareSnapshotRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("captured_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAtUtc")
                        .HasDatabaseName("ix_inventory_hardware_snapshots_captured_at_utc");

                    b.ToTable("inventory_hardware_snapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
