// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wec.Infrastructure.Persistence;

#nullable disable

namespace Wec.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WecDbContext))]
    [Migration("20260908110424_AddInventoryIdentityKey")]
    partial class AddInventoryIdentityKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Wec.Modules.Diagnostics.Persistence.DiagnosticRunRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CompletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("Host")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("host");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.HasKey("Id");

                    b.HasIndex("Host")
                        .IsUnique()
                        .HasDatabaseName("ix_diagnostics_runs_host");

                    b.ToTable("diagnostics_runs", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.EmployeeLifecycle.Persistence.CaseRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CancelReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("cancel_reason");

                    b.Property<long?>("ClosedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("closed_utc");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_utc");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_date");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("employee_lifecycle_cases", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.EmployeeLifecycle.Persistence.CaseTaskRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("area");

                    b.Property<string>("Assignee")
                        .HasColumnType("TEXT")
                        .HasColumnName("assignee");

                    b.Property<long>("CaseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("case_id");

                    b.Property<long?>("CompletedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_utc");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_utc");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_date");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("employee_lifecycle_tasks", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.EmployeeLifecycle.Persistence.DepartmentRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ManagerName")
                        .HasColumnType("TEXT")
                        .HasColumnName("manager_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("OuDistinguishedName")
                        .HasColumnType("TEXT")
                        .HasColumnName("ou_distinguished_name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("employee_lifecycle_departments", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.EmployeeLifecycle.Persistence.EmployeeRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_utc");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT")
                        .HasColumnName("department");

                    b.Property<string>("DistinguishedName")
                        .HasColumnType("TEXT")
                        .HasColumnName("distinguished_name");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_number");

                    b.Property<DateOnly?>("EntryDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_date");

                    b.Property<DateOnly?>("ExitDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("exit_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Manager")
                        .HasColumnType("TEXT")
                        .HasColumnName("manager");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("SamAccountName")
                        .HasColumnType("TEXT")
                        .HasColumnName("sam_account_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_utc");

                    b.Property<string>("UserPrincipalName")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_principal_name");

                    b.HasKey("Id");

                    b.HasIndex("LastName");

                    b.ToTable("employee_lifecycle_employees", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.EmployeeLifecycle.Persistence.LifecycleAuditRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long?>("CaseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("case_id");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT")
                        .HasColumnName("detail");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("old_value");

                    b.Property<long?>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_id");

                    b.Property<long>("TimestampUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("employee_lifecycle_audit_entries", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.Inventory.Persistence.HardwareSnapshotRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CapturedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("captured_at_utc");

                    b.Property<string>("Host")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("host");

                    b.Property<string>("IdentityKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("identity_key");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAtUtc")
                        .HasDatabaseName("ix_inventory_hardware_snapshots_captured_at_utc");

                    b.HasIndex("Host")
                        .HasDatabaseName("ix_inventory_hardware_snapshots_host");

                    b.HasIndex("IdentityKey")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_hardware_snapshots_identity_key")
                        .HasFilter("identity_key IS NOT NULL");

                    b.ToTable("inventory_hardware_snapshots", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.PatchManagement.Persistence.PatchAuditRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("DepotId")
                        .HasColumnType("TEXT")
                        .HasColumnName("depot_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("NewVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("new_version");

                    b.Property<string>("OldVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("old_version");

                    b.Property<string>("PreviewJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("preview_json");

                    b.Property<string>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("result");

                    b.Property<string>("TargetClientsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_clients_json");

                    b.Property<long>("TimestampUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("patchmanagement_audit_entries", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.PatchManagement.Persistence.WingetManagedPackageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CheckStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("check_status");

                    b.Property<long?>("CheckedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("checked_at_utc");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DepotId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("depot_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<string>("LastPackagedWingetVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_packaged_winget_version");

                    b.Property<string>("LatestWingetVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("latest_winget_version");

                    b.Property<string>("OpsiProductId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("opsi_product_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scope");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<int>("TemplateVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("template_version");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("WingetId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("winget_id");

                    b.HasKey("Id");

                    b.HasIndex("OpsiProductId")
                        .IsUnique();

                    b.HasIndex("WingetId", "DepotId")
                        .IsUnique();

                    b.ToTable("patchmanagement_winget_packages", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.PrintManagement.Persistence.ClientPrinterScanRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CapturedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("captured_at_utc");

                    b.Property<string>("Host")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("host");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.HasKey("Id");

                    b.HasIndex("Host")
                        .IsUnique()
                        .HasDatabaseName("ix_printmanagement_client_printer_scans_host");

                    b.ToTable("printmanagement_client_printer_scans", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.PrintManagement.Persistence.PrintSnapshotRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CapturedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("captured_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("server");

                    b.HasKey("Id");

                    b.HasIndex("Server", "CapturedAtUtc");

                    b.ToTable("printmanagement_snapshots", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.Security.Persistence.SecurityCheckResultRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CheckId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("check_id");

                    b.Property<string>("FailureCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_message");

                    b.Property<string>("RequiredPrivilege")
                        .HasColumnType("TEXT")
                        .HasColumnName("required_privilege");

                    b.Property<long>("ScanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scan_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ScanId", "CheckId")
                        .IsUnique()
                        .HasDatabaseName("ux_security_check_results_scan_check");

                    b.ToTable("security_check_results", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.Security.Persistence.SecurityFindingRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AffectedResource")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("affected_resource");

                    b.Property<long>("CapturedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("captured_at_utc");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("CheckId")
                        .HasColumnType("TEXT")
                        .HasColumnName("check_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("evidence_json");

                    b.Property<string>("FindingId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("finding_id");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recommendation");

                    b.Property<string>("RequiredPrivilege")
                        .HasColumnType("TEXT")
                        .HasColumnName("required_privilege");

                    b.Property<long>("ScanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scan_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ScanId")
                        .HasDatabaseName("ix_security_findings_scan_id");

                    b.ToTable("security_findings", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.Security.Persistence.SecurityScanRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CompletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at_utc");

                    b.Property<int?>("CoverageVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("coverage_version");

                    b.Property<int>("FindingCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("finding_count");

                    b.Property<string>("Host")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("host");

                    b.Property<long>("StartedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Host")
                        .HasDatabaseName("ix_security_scans_host");

                    b.ToTable("security_scans", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.Targets.Persistence.SavedTargetRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("host");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Host", "Role")
                        .IsUnique();

                    b.ToTable("targets_saved", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.VulnerabilityManagement.Persistence.NessusAssetRecord", b =>
                {
                    b.Property<string>("AssetKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("asset_key");

                    b.Property<string>("AssetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("asset_id");

                    b.Property<int>("Critical")
                        .HasColumnType("INTEGER")
                        .HasColumnName("critical");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Fqdn")
                        .HasColumnType("TEXT")
                        .HasColumnName("fqdn");

                    b.Property<int>("High")
                        .HasColumnType("INTEGER")
                        .HasColumnName("high");

                    b.Property<string>("HostName")
                        .HasColumnType("TEXT")
                        .HasColumnName("host_name");

                    b.Property<int>("Info")
                        .HasColumnType("INTEGER")
                        .HasColumnName("info");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address");

                    b.Property<long>("LastScanUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_scan_utc");

                    b.Property<int>("Low")
                        .HasColumnType("INTEGER")
                        .HasColumnName("low");

                    b.Property<int>("Medium")
                        .HasColumnType("INTEGER")
                        .HasColumnName("medium");

                    b.Property<string>("PortsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ports_json");

                    b.Property<string>("ScanSourcesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scan_sources_json");

                    b.HasKey("AssetKey");

                    b.HasIndex("HostName")
                        .HasDatabaseName("ix_nessus_assets_host_name");

                    b.ToTable("nessus_assets", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.VulnerabilityManagement.Persistence.NessusFindingRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AssetKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("asset_key");

                    b.Property<string>("CvesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cves_json");

                    b.Property<long>("LastObservedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_observed_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("PluginId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("plugin_id");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER")
                        .HasColumnName("port");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("protocol");

                    b.Property<string>("ScanSourcesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scan_sources_json");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<string>("Solution")
                        .HasColumnType("TEXT")
                        .HasColumnName("solution");

                    b.Property<string>("Synopsis")
                        .HasColumnType("TEXT")
                        .HasColumnName("synopsis");

                    b.HasKey("Id");

                    b.HasIndex("AssetKey", "PluginId", "Port", "Protocol")
                        .IsUnique()
                        .HasDatabaseName("ux_nessus_findings_identity");

                    b.ToTable("nessus_findings", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.VulnerabilityManagement.Persistence.NessusScanRecord", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<bool>("Excluded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("excluded");

                    b.Property<long?>("LatestCompletedHistoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("latest_completed_history_id");

                    b.Property<long?>("LatestCompletedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("latest_completed_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("nessus_scans", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.VulnerabilityManagement.Persistence.NessusStateRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CompletedScans")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_scans");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<bool>("HistorySupported")
                        .HasColumnType("INTEGER")
                        .HasColumnName("history_supported");

                    b.Property<long?>("LastSuccessfulSyncUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_successful_sync_utc");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("phase");

                    b.Property<bool>("Running")
                        .HasColumnType("INTEGER")
                        .HasColumnName("running");

                    b.Property<string>("ServerVersion")
                        .HasColumnType("TEXT")
                        .HasColumnName("server_version");

                    b.Property<long?>("StartedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("TotalScans")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_scans");

                    b.HasKey("Id");

                    b.ToTable("nessus_state", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.VulnerabilityManagement.Persistence.NessusTrendRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AssetKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("asset_key");

                    b.Property<int>("Critical")
                        .HasColumnType("INTEGER")
                        .HasColumnName("critical");

                    b.Property<string>("DayUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("day_utc");

                    b.Property<int>("High")
                        .HasColumnType("INTEGER")
                        .HasColumnName("high");

                    b.Property<int>("Info")
                        .HasColumnType("INTEGER")
                        .HasColumnName("info");

                    b.Property<int>("Low")
                        .HasColumnType("INTEGER")
                        .HasColumnName("low");

                    b.Property<int>("Medium")
                        .HasColumnType("INTEGER")
                        .HasColumnName("medium");

                    b.HasKey("Id");

                    b.HasIndex("DayUtc", "AssetKey")
                        .IsUnique()
                        .HasDatabaseName("ux_nessus_trends_day_asset");

                    b.ToTable("nessus_trends", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.Security.Persistence.SecurityCheckResultRecord", b =>
                {
                    b.HasOne("Wec.Modules.Security.Persistence.SecurityScanRecord", null)
                        .WithMany("CheckResults")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wec.Modules.Security.Persistence.SecurityFindingRecord", b =>
                {
                    b.HasOne("Wec.Modules.Security.Persistence.SecurityScanRecord", null)
                        .WithMany("Findings")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wec.Modules.Security.Persistence.SecurityScanRecord", b =>
                {
                    b.Navigation("CheckResults");

                    b.Navigation("Findings");
                });
#pragma warning restore 612, 618
        }
    }
}
