// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wec.Infrastructure.Persistence;

#nullable disable

namespace Wec.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WecDbContext))]
    [Migration("20260702125810_AddSecurityScans")]
    partial class AddSecurityScans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("Wec.Modules.Inventory.Persistence.HardwareSnapshotRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CapturedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("captured_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAtUtc")
                        .HasDatabaseName("ix_inventory_hardware_snapshots_captured_at_utc");

                    b.ToTable("inventory_hardware_snapshots", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.Security.Persistence.SecurityFindingRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AffectedResource")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("affected_resource");

                    b.Property<long>("CapturedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("captured_at_utc");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("evidence_json");

                    b.Property<string>("FindingId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("finding_id");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recommendation");

                    b.Property<string>("RequiredPrivilege")
                        .HasColumnType("TEXT")
                        .HasColumnName("required_privilege");

                    b.Property<long>("ScanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scan_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ScanId")
                        .HasDatabaseName("ix_security_findings_scan_id");

                    b.ToTable("security_findings", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.Security.Persistence.SecurityScanRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CompletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at_utc");

                    b.Property<int>("FindingCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("finding_count");

                    b.Property<long>("StartedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("security_scans", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.Security.Persistence.SecurityFindingRecord", b =>
                {
                    b.HasOne("Wec.Modules.Security.Persistence.SecurityScanRecord", null)
                        .WithMany("Findings")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wec.Modules.Security.Persistence.SecurityScanRecord", b =>
                {
                    b.Navigation("Findings");
                });
#pragma warning restore 612, 618
        }
    }
}
