// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wec.Infrastructure.Persistence;

#nullable disable

namespace Wec.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WecDbContext))]
    [Migration("20260708113629_AddDiagnosticAndClientPrinterPersistence")]
    partial class AddDiagnosticAndClientPrinterPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Wec.Modules.Diagnostics.Persistence.DiagnosticRunRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CompletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("Host")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("host");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.HasKey("Id");

                    b.HasIndex("Host")
                        .IsUnique()
                        .HasDatabaseName("ix_diagnostics_runs_host");

                    b.ToTable("diagnostics_runs", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.Inventory.Persistence.HardwareSnapshotRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CapturedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("captured_at_utc");

                    b.Property<string>("Host")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("host");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAtUtc")
                        .HasDatabaseName("ix_inventory_hardware_snapshots_captured_at_utc");

                    b.HasIndex("Host")
                        .HasDatabaseName("ix_inventory_hardware_snapshots_host");

                    b.ToTable("inventory_hardware_snapshots", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.PatchManagement.Persistence.PatchAuditRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("DepotId")
                        .HasColumnType("TEXT")
                        .HasColumnName("depot_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("PreviewJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("preview_json");

                    b.Property<string>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("result");

                    b.Property<string>("TargetClientsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_clients_json");

                    b.Property<long>("TimestampUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("patchmanagement_audit_entries", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.PatchManagement.Persistence.ProductMappingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("OpsiProductId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("opsi_product_id");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("software_name");

                    b.HasKey("Id");

                    b.HasIndex("SoftwareName")
                        .IsUnique();

                    b.ToTable("patchmanagement_product_mappings", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.PrintManagement.Persistence.ClientPrinterScanRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CapturedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("captured_at_utc");

                    b.Property<string>("Host")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("host");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.HasKey("Id");

                    b.HasIndex("Host")
                        .IsUnique()
                        .HasDatabaseName("ix_printmanagement_client_printer_scans_host");

                    b.ToTable("printmanagement_client_printer_scans", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.PrintManagement.Persistence.PrintSnapshotRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CapturedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("captured_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload_json");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("server");

                    b.HasKey("Id");

                    b.HasIndex("Server", "CapturedAtUtc");

                    b.ToTable("printmanagement_snapshots", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.Security.Persistence.SecurityFindingRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AffectedResource")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("affected_resource");

                    b.Property<long>("CapturedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("captured_at_utc");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("evidence_json");

                    b.Property<string>("FindingId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("finding_id");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recommendation");

                    b.Property<string>("RequiredPrivilege")
                        .HasColumnType("TEXT")
                        .HasColumnName("required_privilege");

                    b.Property<long>("ScanId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scan_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ScanId")
                        .HasDatabaseName("ix_security_findings_scan_id");

                    b.ToTable("security_findings", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.Security.Persistence.SecurityScanRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CompletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at_utc");

                    b.Property<int>("FindingCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("finding_count");

                    b.Property<string>("Host")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("host");

                    b.Property<long>("StartedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Host")
                        .HasDatabaseName("ix_security_scans_host");

                    b.ToTable("security_scans", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.Targets.Persistence.SavedTargetRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("host");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Host", "Role")
                        .IsUnique();

                    b.ToTable("targets_saved", (string)null);
                });

            modelBuilder.Entity("Wec.Modules.Security.Persistence.SecurityFindingRecord", b =>
                {
                    b.HasOne("Wec.Modules.Security.Persistence.SecurityScanRecord", null)
                        .WithMany("Findings")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wec.Modules.Security.Persistence.SecurityScanRecord", b =>
                {
                    b.Navigation("Findings");
                });
#pragma warning restore 612, 618
        }
    }
}
