using System.Globalization;
using System.Net;
using System.Text;
using Wec.Core.Contracts;

namespace Wec.Modules.Reporting.Application;

/// <summary>
/// Pure function from context to a self-contained HTML document (inline CSS,
/// no external assets, printable) — deterministic and therefore testable.
/// </summary>
internal static class ExecutiveSummaryHtmlGenerator
{
    public static string Generate(ExecutiveSummaryContext context)
    {
        var html = new StringBuilder();
        html.Append("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">");
        html.Append(CultureInfo.InvariantCulture,
            $"<title>WEC Executive Summary — {H(context.MachineName)}</title>");
        html.Append("<style>").Append(Stylesheet).Append("</style></head><body>");

        AppendHeader(html, context);
        AppendReadiness(html, context.Readiness);
        AppendSecuritySection(html, context.SecurityScan);
        AppendInventorySection(html, context.Inventory);

        html.Append(CultureInfo.InvariantCulture,
            $"<footer>Generated by Windows Enterprise Companion v{H(context.AppVersion)} — read-only assessment of {H(context.MachineName)}.</footer>");
        html.Append("</body></html>");
        return html.ToString();
    }

    private static void AppendReadiness(StringBuilder html, ReportReadiness readiness)
    {
        string readinessClass = readiness.IsReady ? "coverage-ok" : "coverage-warning";
        string label = readiness.IsReady ? "Ready to export" : "Refresh or complete data before relying on this report";
        html.Append(CultureInfo.InvariantCulture,
            $"<section><h2>Report readiness</h2><p class=\"{readinessClass}\"><strong>{H(label)}.</strong></p>");
        html.Append("<table class=\"data\"><thead><tr><th>Source</th><th>State</th><th>Age</th><th>Provenance</th><th>Assessment</th></tr></thead><tbody>");
        foreach (ReportSourceReadiness source in readiness.Sources)
        {
            string age = source.AgeSeconds is long seconds ? FormatAge(seconds) : "—";
            html.Append(CultureInfo.InvariantCulture,
                $"<tr><td>{H(source.Source)}</td><td>{H(Humanize(source.State))}</td><td>{H(age)}</td><td>{H(source.Provenance)}</td><td>{H(source.Summary)}</td></tr>");
        }

        html.Append("</tbody></table></section>");
    }

    private static void AppendHeader(StringBuilder html, ExecutiveSummaryContext context)
    {
        html.Append("<header><h1>Executive Summary</h1>");
        html.Append("<table class=\"meta\">");
        html.Append(CultureInfo.InvariantCulture, $"<tr><th>Machine</th><td>{H(context.MachineName)}</td></tr>");
        html.Append(CultureInfo.InvariantCulture, $"<tr><th>Generated (UTC)</th><td>{Ts(context.GeneratedAtUtc)}</td></tr>");
        html.Append("</table></header>");
    }

    private static void AppendSecuritySection(StringBuilder html, SecurityReportData? scan)
    {
        html.Append("<section><h2>Security posture</h2>");
        if (scan is null)
        {
            html.Append("<p class=\"nodata\">No security scan has been run on this machine yet.</p></section>");
            return;
        }

        html.Append(CultureInfo.InvariantCulture,
            $"<p>Latest scan completed {Ts(scan.CompletedAtUtc)} — status {H(Humanize(scan.Status))}, {scan.Findings.Count} findings.</p>");

        AppendSecurityCoverage(html, scan);

        if (scan.Findings.Count > 0)
        {
            html.Append("<p class=\"chips\">");
            foreach (IGrouping<string, SecurityFindingReportData> group in scan.Findings
                .GroupBy(finding => finding.Severity)
                .OrderByDescending(group => group.Max(finding => finding.SeverityRank)))
            {
                html.Append(CultureInfo.InvariantCulture,
                    $"<span class=\"chip sev-{H(group.Key.ToLowerInvariant())}\">{H(group.Key.ToUpperInvariant())}: {group.Count().ToString(CultureInfo.InvariantCulture)}</span> ");
            }

            html.Append("</p><table class=\"data\"><thead><tr>"
                + "<th>Severity</th><th>Finding</th><th>Affected resource</th><th>Recommendation</th>"
                + "</tr></thead><tbody>");
            foreach (SecurityFindingReportData finding in scan.Findings
                .OrderByDescending(finding => finding.SeverityRank)
                .ThenBy(finding => finding.FindingId, StringComparer.Ordinal))
            {
                string elevationNote = finding.RequiredPrivilege is null
                    ? string.Empty
                    : $"<br><em>Not evaluated without elevation (requires {H(finding.RequiredPrivilege)}).</em>";
                html.Append(CultureInfo.InvariantCulture,
                    $"<tr><td class=\"sev-{H(finding.Severity.ToLowerInvariant())}\">{H(finding.Severity.ToUpperInvariant())}</td><td><strong>{H(finding.Title)}</strong><br>{H(finding.Description)}{elevationNote}</td><td>{H(finding.AffectedResource)}</td><td>{H(finding.Recommendation)}</td></tr>");
            }

            html.Append("</tbody></table>");
        }
        else
        {
            bool isPass = scan.Coverage.IsComplete
                && string.Equals(scan.Status, "Completed", StringComparison.Ordinal);
            html.Append(isPass
                ? "<p class=\"coverage-ok\"><strong>PASS:</strong> No security findings were observed and all applicable checks completed successfully.</p>"
                : "<p class=\"coverage-warning\"><strong>No security findings were observed.</strong> This scan is not a PASS because coverage or execution was incomplete or unavailable.</p>");
        }

        html.Append("</section>");
    }

    private static void AppendSecurityCoverage(StringBuilder html, SecurityReportData scan)
    {
        SecurityCoverageReportData coverage = scan.Coverage;
        if (!coverage.IsKnown)
        {
            html.Append("<p class=\"coverage-warning\"><strong>Coverage unavailable.</strong> "
                + "Per-check execution tracking is absent or inconsistent, for example on a legacy scan. "
                + "The scan must not be interpreted as complete.</p>");
            return;
        }

        string coverageClass = coverage.IsComplete ? "coverage-ok" : "coverage-warning";
        string coverageLabel = coverage.IsComplete ? "Coverage complete" : "Coverage incomplete";
        html.Append(CultureInfo.InvariantCulture,
            $"<p class=\"{coverageClass}\"><strong>{coverageLabel}:</strong> {coverage.SucceededChecks} of {coverage.ApplicableChecks} applicable checks completed successfully. Failed: {coverage.FailedChecks}; requires elevation: {coverage.RequiresElevationChecks}; not applicable: {coverage.NotApplicableChecks}.</p>");

        List<SecurityCheckReportData> checksWithoutResult = scan.CheckResults
            .Where(result => !string.Equals(result.Status, "Succeeded", StringComparison.Ordinal))
            .OrderBy(result => result.CheckId, StringComparer.Ordinal)
            .ToList();
        if (checksWithoutResult.Count == 0)
        {
            return;
        }

        html.Append("<h3>Checks without an evaluated result</h3>"
            + "<table class=\"data\"><thead><tr><th>Check</th><th>Status</th><th>Reason</th></tr></thead><tbody>");
        foreach (SecurityCheckReportData check in checksWithoutResult)
        {
            string reason = check.Failure is null
                ? "No failure details were recorded."
                : $"{check.Failure.Message} ({Humanize(check.Failure.Code)})"
                    + (check.Failure.RequiredPrivilege is null
                        ? string.Empty
                        : $" Requires {Humanize(check.Failure.RequiredPrivilege)}.");
            html.Append(CultureInfo.InvariantCulture,
                $"<tr><td>{H(check.CheckId)}</td><td>{H(Humanize(check.Status))}</td><td>{H(reason)}</td></tr>");
        }

        html.Append("</tbody></table>");
    }

    private static void AppendInventorySection(StringBuilder html, InventoryReportData? inventory)
    {
        html.Append("<section><h2>Hardware inventory</h2>");
        if (inventory is null)
        {
            html.Append("<p class=\"nodata\">No hardware snapshot has been captured on this machine yet.</p></section>");
            return;
        }

        html.Append(CultureInfo.InvariantCulture, $"<p>Snapshot captured {Ts(inventory.CapturedAtUtc)}.</p>");
        html.Append("<table class=\"meta\">");
        html.Append(CultureInfo.InvariantCulture,
            $"<tr><th>CPU</th><td>{H(inventory.Cpu.Name)} — {inventory.Cpu.PhysicalCores.ToString(CultureInfo.InvariantCulture)} physical / "
            + $"{inventory.Cpu.LogicalProcessors.ToString(CultureInfo.InvariantCulture)} logical cores, "
            + $"max {inventory.Cpu.MaxClockSpeedMhz.ToString(CultureInfo.InvariantCulture)} MHz</td></tr>");
        html.Append(CultureInfo.InvariantCulture,
            $"<tr><th>Operating system</th><td>{H(inventory.OperatingSystem.Caption)} — {H(inventory.OperatingSystem.Version)} "
            + $"(build {H(inventory.OperatingSystem.BuildNumber)}, {H(inventory.OperatingSystem.Architecture ?? "unknown architecture")})</td></tr>");
        html.Append(CultureInfo.InvariantCulture,
            $"<tr><th>Memory</th><td>{Gb(inventory.MemoryBanks.Sum(bank => bank.CapacityBytes))} in "
            + $"{inventory.MemoryBanks.Count.ToString(CultureInfo.InvariantCulture)} banks</td></tr>");
        html.Append("</table>");

        html.Append("<h3>Disks</h3><table class=\"data\"><thead><tr><th>Model</th><th>Size</th><th>Interface</th></tr></thead><tbody>");
        foreach (DiskReportData disk in inventory.Disks)
        {
            html.Append(CultureInfo.InvariantCulture,
                $"<tr><td>{H(disk.Model)}</td><td>{Gb(disk.SizeBytes)}</td><td>{H(disk.InterfaceType ?? "—")}</td></tr>");
        }

        html.Append("</tbody></table></section>");
    }

    private static string H(string value) => WebUtility.HtmlEncode(value);

    private static string Ts(DateTimeOffset timestamp) =>
        timestamp.UtcDateTime.ToString("yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture) + " UTC";

    private static string Gb(long bytes) =>
        (bytes / 1073741824d).ToString("F1", CultureInfo.InvariantCulture) + " GB";

    private static string FormatAge(long ageSeconds)
    {
        TimeSpan age = TimeSpan.FromSeconds(ageSeconds);
        if (age.TotalDays >= 1)
        {
            return $"{Math.Floor(age.TotalDays).ToString(CultureInfo.InvariantCulture)}d {age.Hours.ToString(CultureInfo.InvariantCulture)}h";
        }

        if (age.TotalHours >= 1)
        {
            return $"{Math.Floor(age.TotalHours).ToString(CultureInfo.InvariantCulture)}h {age.Minutes.ToString(CultureInfo.InvariantCulture)}m";
        }

        return $"{Math.Max(0, age.Minutes).ToString(CultureInfo.InvariantCulture)}m";
    }

    private static string Humanize(string pascalCaseValue)
    {
        var text = new StringBuilder();
        foreach (char character in pascalCaseValue)
        {
            if (char.IsUpper(character) && text.Length > 0)
            {
                text.Append(' ');
            }

            text.Append(character);
        }

        return text.ToString();
    }

    private const string Stylesheet =
        "body{font-family:Segoe UI,system-ui,sans-serif;color:#1a2333;margin:2rem auto;max-width:60rem;padding:0 1rem}"
        + "h1{font-size:1.6rem;border-bottom:2px solid #1a2333;padding-bottom:.4rem}"
        + "h2{font-size:1.2rem;margin-top:2rem}h3{font-size:1rem}"
        + "table{border-collapse:collapse;width:100%}"
        + "table.meta th{text-align:left;padding:.2rem .8rem .2rem 0;white-space:nowrap;vertical-align:top}"
        + "table.meta td{padding:.2rem 0}"
        + "table.data{margin-top:.5rem}table.data th,table.data td{border:1px solid #c4ccd8;padding:.4rem .6rem;text-align:left;vertical-align:top;font-size:.9rem}"
        + "table.data thead{background:#eef1f6}"
        + ".chip{display:inline-block;border:1px solid #c4ccd8;border-radius:.3rem;padding:.1rem .5rem;font-size:.8rem;font-weight:600}"
        + ".sev-critical,.sev-high{color:#a11a1a}.sev-medium{color:#9a6700}.sev-low{color:#0a5da0}.sev-info{color:#4a5568}"
        + ".coverage-ok{color:#176b3a}.coverage-warning{color:#8a5700}"
        + ".nodata{color:#4a5568;font-style:italic}"
        + "footer{margin-top:3rem;font-size:.8rem;color:#4a5568;border-top:1px solid #c4ccd8;padding-top:.5rem}"
        + "@media print{body{margin:0;max-width:none}}";
}
