<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Wec.Core\Wec.Core.csproj" />
    <ProjectReference Include="..\..\src\Wec.Infrastructure\Wec.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Wec.Modules.Diagnostics\Wec.Modules.Diagnostics.csproj" />
    <ProjectReference Include="..\..\src\Modules\Wec.Modules.EmployeeLifecycle\Wec.Modules.EmployeeLifecycle.csproj" />
    <ProjectReference Include="..\..\src\Modules\Wec.Modules.Inventory\Wec.Modules.Inventory.csproj" />
    <ProjectReference Include="..\..\src\Modules\Wec.Modules.Security\Wec.Modules.Security.csproj" />
    <ProjectReference Include="..\..\src\Modules\Wec.Modules.PatchManagement\Wec.Modules.PatchManagement.csproj" />
    <ProjectReference Include="..\..\src\Modules\Wec.Modules.PrintManagement\Wec.Modules.PrintManagement.csproj" />
    <ProjectReference Include="..\..\src\Modules\Wec.Modules.Targets\Wec.Modules.Targets.csproj" />
    <ProjectReference Include="..\..\src\Modules\Wec.Modules.VulnerabilityManagement\Wec.Modules.VulnerabilityManagement.csproj" />
  </ItemGroup>

</Project>
